### ISSUE TITLE
Wrong compilation

### ISSUE THREAD

**Issue by KalleDK** [michaelrsweet/abnf#1]
If I understand the following syntax correct - FWS is at least a A or B in the end with and optional amount of A or B before and optional CD

```
CR = %d43
LF = %d44
WSP = %d41 / %d42
FWS = [*WSP CR LF] 1*WSP
```

Valid
```
AAAACDAAA
BABCDBA
CDA
A
AAAABBA
AA
```

Invalid
```
AACD
CAA
AAD
DA
```

But the regex produced is

^((A|B)*CD){0,1}$

Which is missing the end A or B ( again if I read correct)

**Comment by KalleDK** [comment]
Aaah it's the repition rule it can't parse

1*WSP gives  ^$

**Comment by KalleDK** [comment]
The * was not showing in the start of the code

**Comment by michaelrsweet** [comment]
@KalleDK Could you clarify your comment?

From my own testing of the above ABNF, it looks like it isn't adding the last token to the rules array...

**Comment by michaelrsweet** [comment]
[master c190785] Add missing token at the end of a rule set.

**Comment by KalleDK** [comment]
The last comment was just that github didn't show the * in the first post. And you closed before i could answer ;)

**Comment by KalleDK** [comment]
Seems to work correct now :)
