### ISSUE TITLE
Error with conversion of ABNF terminal values lower than %d32 or %127

### ISSUE THREAD

**Issue by LSerge13330** [michaelrsweet/abnf#10]

**Comment by LSerge13330** [comment]
**abnf_regex** function "rule1 = %x01-1F / %x30-39 / %x7F" returns "^([-0-9]|)$" with non printable characters.

The problem is due to the following line : **regex .= preg_quote(chr($ch));** 
To handle the non printable codes, the function can be corrected by replacing the corresponding line by :

if ($ch < 32 || $ch == 127) 
{
  // Control codes
  $regex .= "\\x";
  if($ch < 16) {
    $regex .= "0";
  }
  $regex .= strtolower(dechex($ch));
}
else
{
  // Printable characters with escape of characters : . \ + * ? [ ^ ] $ ( ) { } = ! < > | : - #
  // However preg_quote does not naturally escape slash (/) character, so add it as delimiter. 
  // See https://www.php.net/manual/fr/function.preg-quote.php#80049
  $regex .= preg_quote(chr($ch), '/');
}

**Comment by michaelrsweet** [comment]
[master 46d4229] Fix quoting of control characters and slash (Issue #10)
