### ISSUE TITLE
Online Form unvailable

### ISSUE THREAD

**Issue by DontShootMe** [michaelrsweet/abnf#2]
Hello,

I have discover your tool today and wanted to try it from :
[online form](https://abnf.msweet.org) 

the link under https://www.msweet.org/abnf/
But this lead to an unreachable page !

Thank you for all your work, really great.

**Comment by michaelrsweet** [comment]
Sorry, had a VPS upgrade and Apache didn't start up after the update for some reason. It's working now.

**Comment by DontShootMe** [comment]
Tanks for your reactivity !
