### ISSUE TITLE
Improve RegEx style

### ISSUE THREAD

**Issue by mxmlnkn** [michaelrsweet/abnf#8]
Some RegEx parts could be improved upon on:

  - `h = WSP` gets converted into `^( |	)$`. I'd find it better to print `^[ \t]$` instead
  - Similarly combinations of one character elements gets translated to `(|)` syntax instead of better `[]` syntax.
  - `h = [ "a" ]` gets translated to `^[Aa]{0,1}$`. I don't know what restrictions you give to the output RegEx but I'd find `^[Aa]?$` to be more readable
  - Similarly `h = 2("a")` results in `^[Aa]{2,2}$` when `^[Aa]{2}$` would suffice.
  - `h = CRLF` results in ``

**Comment by michaelrsweet** [comment]
Yes, merging single-character rules like WSP (SP / HTAB) or ["a"] to the bracketed regex form would be nice.

IIRC there was some issue with just {N} repeat counts, but I'll double-check as it would indeed be more efficient/readable.

WRT CRLF, that would be Issue #9 and it is all about whether a regular expression matches across a line/record boundary.

**Comment by michaelrsweet** [comment]
[master 68219f8] Optimize repetition counts and WSP content (Issue #8)
